_target_: src.cc_utils.clustering.ModularityBasedClustering
clusteringParameters:
  position_path: ../../data/Input/noaa_coastwatch_cellular/longlat.mat
  position_name: longlat
  best_n: 7
  resolution: 1.5
  dim: 1
  Q-hop: 5