_target_: src.implementations.models.ccvar.CCVARModel
_convert_: partial
algorithmParam:
  Tstep: 6
  P: 2
  K:
  - 2
  - - 2
    - 2
  - 2
  mu:
  - 0
  - - 0
    - 0
  - 0
  lambda: 0.01
  gamma: 0.98
  enabler:
  - true
  - true
  - true
  FeatureNormalzn: true
  BiasEn: true